resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: githubIntegration                      # <-- replace with your integration
      path: elanabakst-github/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: dbp_image
    type: Image
    configuration:
      registry: artifactoryintergration                                # <-- replace with your artifactory integration
      sourceRepository: example-repo-local               # <-- required if registry is Artifactory
      imageName:  https://elanafree.jfrog.io/artifactory/example-repo-local/ < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryintergration
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryintergration
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: pipeline_dbp
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: https://elanafree.jfrog.io/artifactory/example-repo-local/  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: artifactoryintergration                            # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: example-repo-local
          integrations:
            - name: artifactoryintergration                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: demo-pipelines
          integrations:
            - name: artifactoryintergration
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info

